import nodemailer from 'nodemailer';

export interface EmailOptions {
  to: string;
  subject: string;
  name: string;
  senderEmail: string;
  message: string;
}

let cachedTransporter: nodemailer.Transporter | null = null;

async function getTransporter(): Promise<{ transporter: nodemailer.Transporter; isEthereal: boolean }> {
  const host = process.env.SMTP_HOST;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  // If real SMTP credentials are provided
  if (host && user && pass) {
    if (!cachedTransporter) {
      cachedTransporter = nodemailer.createTransport({
        host,
        port: Number(process.env.SMTP_PORT) || 587,
        secure: process.env.SMTP_SECURE === 'true',
        auth: { user, pass },
      });
    }
    return { transporter: cachedTransporter, isEthereal: false };
  }

  // Fallback to Ethereal Test Account
  if (!cachedTransporter) {
    try {
      const testAccount = await nodemailer.createTestAccount();
      cachedTransporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass,
        },
      });
      console.log(`[EmailService] Created Nodemailer Ethereal test account: ${testAccount.user}`);
    } catch (err) {
      console.warn('[EmailService] Failed to create Ethereal account, using JSON transport fallback:', err);
      // Fallback to JSON transport
      cachedTransporter = nodemailer.createTransport({
        jsonTransport: true,
      });
    }
  }

  return { transporter: cachedTransporter, isEthereal: true };
}

export async function sendContactNotificationEmail(options: EmailOptions) {
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@csportal.edu';
  const { transporter, isEthereal } = await getTransporter();

  const formattedHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; rounded: 8px; background-color: #ffffff;">
      <div style="background-color: #4f46e5; padding: 16px; border-radius: 6px; text-align: center; color: white;">
        <h2 style="margin: 0; font-size: 20px;">CS Portal Admin Notification</h2>
        <p style="margin: 4px 0 0 0; font-size: 12px; opacity: 0.9;">New Contact Form Submission Received</p>
      </div>

      <div style="padding: 20px 0; border-bottom: 1px solid #e2e8f0;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: bold; width: 120px;">Sender Name:</td>
            <td style="padding: 8px 0; color: #0f172a; font-size: 14px; font-weight: bold;">${options.name}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: bold;">Sender Email:</td>
            <td style="padding: 8px 0; color: #4f46e5; font-size: 14px; font-weight: bold;">
              <a href="mailto:${options.senderEmail}" style="color: #4f46e5; text-decoration: none;">${options.senderEmail}</a>
            </td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: bold;">Subject:</td>
            <td style="padding: 8px 0; color: #0f172a; font-size: 14px;">${options.subject || 'General Inquiry'}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: bold;">Timestamp:</td>
            <td style="padding: 8px 0; color: #64748b; font-size: 12px;">${new Date().toLocaleString()}</td>
          </tr>
        </table>
      </div>

      <div style="padding: 20px 0;">
        <p style="margin: 0 0 8px 0; color: #64748b; font-size: 13px; font-weight: bold; uppercase;">Message Body:</p>
        <div style="background-color: #f8fafc; padding: 16px; border-radius: 6px; border-left: 4px solid #4f46e5; color: #1e293b; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">
${options.message}
        </div>
      </div>

      <div style="padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px;">
        This automated notification was generated by the Computer Science Portal backend system via Nodemailer.
      </div>
    </div>
  `;

  const mailOptions = {
    from: `"CS Portal System" <noreply@csportal.edu>`,
    to: adminEmail,
    replyTo: options.senderEmail,
    subject: `[CS Portal Inquiry] ${options.subject || 'New Contact Submission'} from ${options.name}`,
    text: `New Contact Form Submission\n\nName: ${options.name}\nEmail: ${options.senderEmail}\nSubject: ${options.subject}\n\nMessage:\n${options.message}`,
    html: formattedHtml,
  };

  const info = await transporter.sendMail(mailOptions);
  let previewUrl: string | undefined;

  if (isEthereal) {
    previewUrl = nodemailer.getTestMessageUrl(info) || undefined;
    if (previewUrl) {
      console.log(`[Nodemailer] Email sent! Ethereal Preview URL: ${previewUrl}`);
    }
  }

  return {
    messageId: info.messageId,
    adminEmail,
    previewUrl,
  };
}
